backend:
  # Use netlify identity as backend
  name: git-gateway
  # branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter

media_library:
  name: cloudinary
  config:
    cloud_name: chicagoland-plumbing
    api_key: 231229224968195
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# publish_mode: editorial_workflow
collections:
  - label: "Articles"
    name: "article"
    label_singular: "Article"
    folder: "src/articles"
    path: "{{tags}}/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Article", name: "featured", widget: "boolean"}
      - { label: "Page URL", name: "slug", widget: "string"}
      - widget: select
        label: "Categroy"
        name: "tags"
        multiple: false
        options: 
          -  { label: "Water Filtration", value: "water-filtration" }
          -  { label: "Plumbing Tips", value: "plumbing-tips" }
          -  { label: "DIY", value: "diy" }
          -  { label: "Ask A Plumber", value: "ask-a-plumber" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Snippet", name: "snippet", widget: "string" }
      - { label: "Header Image", name: "image", widget: "image"}
      # - { label: "Publish Date", name: "date", widget: "date", format: "DD MM YYYY hh:mm:ss" }
      - { label: "Intro Section", name: "intro", widget: "markdown"}
      - label: "Article Section"
        name: "articleSection"
        widget: "list"
        label_singular: "Article Section"
        collapsed: true
        fields: 
          - { label: "Section Name", name: "sectionName", widget: "string" }
          - { label: "Section Quick Link", name: "sectionLink", widget: "string" }
          - { label: "Section Content", name: "sectionContent", widget: "markdown"}
      

  - label: "Commercial Services"
    serviceCategory: "Commercial Service"
    name: "commercial-services"
    folder: "src/services/commercial-services"
    # file: "src/services/commercial-services_index.json"
    identifier_field: name
    # extension: "json"
    slug: "{{fields.slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page URL", name: "slug", widget: "string"}
      - { label: "Snippet", name: "snippet", widget: "string"}
      - { label: "Details", name: "details", widget: "text"}
      - { label: "Service Images", name: "image", widget: "image"}
      - { label: "Chat Link", name: "chatLink", widget: "string"}
      - label: "Features"
        name: "feature"
        widget: "select"
        multiple: true
        options: ["Fast Installation", "Lower Energy Cost","Eco-Friendly", "Annual Inspection Req.", "Special Savings", "Cleaner Water", "Instant Hot Water", "Lifetime Warranty", "1 Year Warranty", "2 Year Warranty", "3 Year Warranty", 4 Year Warranty", "5 Year Warranty", "Premium Quality", "Wifi Enabled"]
      - label: "Service FAQs"
        name: "service-faqs"
        widget: "list"
        summary: '{{fields.Question}}}'
        fields:
            - {label: "Question", name: "question", widget: string}
            - {label: "Answer", name: "answer", widget: string}
      
      # - label: "Icons"
      #   name: "serviceIcons"
      #   widget: "list"
      #   label_singular: "icon"
      #   collapsed: true
      #   fields: 
      #     - { label: "Service Icon", name: "serviceIcon", widget: "string" }
      #     - { label: "Icon Title", name: "iconTitle", widget: "string" }

  - label: "Residential Services"
    serviceCategory: "Residential Service"
    name: "residential-services"
    folder: "src/services/residential-services"
    identifier_field: name
    # extension: "json"
    slug: "{{fields.slug}}"
    create: true
    fields:
      - label: "SEO"
        name: "seo"
        widget: "list"
        allow_add: false
        description: "These fields are for Search Engine Optimization. They will not directly impact the page content."
        fields:
          - {label: "Meta Title", name: "metaTitle", widget: "string", pattern: ["^.{5,60}$", "Must be between 5 and 60 characters long."], description: "The meta title will display the title of the page in the page tab. For more info visit ==>  https://www.searchmetrics.com/glossary/page-title/"}
          - {label: "Meta Description", name: "metaDescription", widget: "text", pattern: ["^.{50,160}$", "Must be between 50 and 160 characters long."], description: "The meta description will display a description of the page in search engines. For more info visit ==>  https://www.searchmetrics.com/glossary/meta-description/"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page URL", name: "slug", widget: "string"}
      - { label: "Snippet", name: "snippet", widget: "string"}
      - { label: "Details", name: "details", widget: "text"}
      - { label: "Service Image", name: "image", widget: "image"}
      - { label: "Image File Name", name: "imageFileName", widget: "string", description: "The image file name is needed in order to optimize the image across the site. To find where the file name is, visit ==> http://bit.ly/37QtFWh"}
      - label: "Features"
        name: "feature"
        widget: "select"
        multiple: true
        options: ["Fast Installation", "Lower Energy Cost","Eco-Friendly", "Annual Inspection Req.", "Special Savings", "Cleaner Water", "Instant Hot Water", "Lifetime Warranty", "1 Year Warranty", "2 Year Warranty", "3 Year Warranty", 4 Year Warranty", "5 Year Warranty", "Premium Quality", "Wifi Enabled"]
      - label: "Service FAQs"
        name: "serviceFaqs"
        widget: "list"
        collapsed: true
        summary: '{{fields.question}}'
        fields:
            - {label: "Question", name: "question", widget: string}
            - {label: "Answer", name: "answer", widget: string}

  - label: "New Construction Services"
    serviceCategory: "New Construction Service"
    name: "new-construction-services"
    folder: "src/services/new-construction-services"
    identifier_field: name
    # extension: "json"
    slug: "{{fields.slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page URL", name: "slug", widget: "string"}
      - { label: "Snippet", name: "snippet", widget: "string"}
      - { label: "Details", name: "details", widget: "text"}
      - { label: "Service Images", name: "image", widget: "image"}
      - { label: "Chat Link", name: "chatLink", widget: "string"}
      - label: "Features"
        name: "feature"
        widget: "select"
        multiple: true
        options: ["Fast Installation", "Lower Energy Cost","Eco-Friendly", "Annual Inspection Req.", "Special Savings", "Cleaner Water", "Instant Hot Water", "Lifetime Warranty", "1 Year Warranty", "2 Year Warranty", "3 Year Warranty", 4 Year Warranty", "5 Year Warranty", "Premium Quality", "Wifi Enabled"]
      - label: "Frequently Asked Questions"
        name: "service-faqs"
        widget: "list"
        summary: '{{fields.question}}'
        fields:
            - {label: "Question", name: "question", widget: string}
            - {label: "Answer", name: "answer", widget: string}

  - label: "Authors"
    name: "authors"
    folder: "src/authors"
    identifier_field: name
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Bio", name: "bio", widget: "text"}
      -  label: "Service Images" 
         name: "image"
         widget: "image"

          
  

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }

  - label: "All Widgets"
    name: "allWidgets"
    files:
      - label: "Blog Post Hero Image"
        name: "blogPostHeroImage"
        widget: "list"
        file: "src/_data/settings.yaml"
        fields: 
          - label: Hero Image
            name: heroImage
            widget: object
            minimized_collapsed: true
            allow_add: true
            collapsed: true
            fields:
              - {label: Hero Image, name: image, widget: image}
              - { label: Image Title, name: title, widget: string}
          - label: Post Title
            name: postTitle
            widget: string

  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: source/handbook
    create: true
    encoding: "ascii"
    clean_accents: true
    sanitize_replacement: "-"
    nested: { depth: 100, summary: '{{title}}' } # accepts an optional summary template
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
  
          

        
