backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: tripj/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Articles"
    name: "article"
    folder: "src/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date", format: "MMMM Do YYYY" }
      - { label: "Intro Section", name: "intro", widget: "markdown"}
      - label: "Article Section"
        name: "articleSection"
        widget: "list"
        label_singular: "Article Section"
        collapsed: true
        fields: 
          - { label: "Section Name", name: "sectionName", widget: "string" }
          - { label: "Section Quick Link", name: "sectionLink", widget: "string" }
          - { label: "Section Content", name: "sectionContent", widget: "markdown"}
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

  - label: "Commercial Services"
    serviceCategory: "Commercial Service"
    name: "commercial-services"
    folder: "src/services/commercial-services"
    # file: "src/services/commercial-services_index.json"
    identifier_field: name
    # extension: "json"
    slug: "{{fields.slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page URL", name: "slug", widget: "string"}
      - { label: "Snippet", name: "snippet", widget: "string"}
      - { label: "Details", name: "details", widget: "text"}
      - { label: "Service Images", name: "image", widget: "image"}
     
      - label: "Features"
        name: "feature"
        widget: "select"
        options: ["Fast Installation", "Lower Energy Cost","Eco-Friendly", "Annual Inspection Req.", "Special Savings", "Cleaner Water", "Instant Hot Water", "Lifetime Warranty", "1 Year Warranty", "2 Year Warranty", "3 Year Warranty", 4 Year Warranty", "5 Year Warranty", "Premium Quality", "Wifi Enabled"]


      # - label: "Icons"
      #   name: "serviceIcons"
      #   widget: "list"
      #   label_singular: "icon"
      #   collapsed: true
      #   fields: 
      #     - { label: "Service Icon", name: "serviceIcon", widget: "string" }
      #     - { label: "Icon Title", name: "iconTitle", widget: "string" }

  - label: "Residential Services"
    serviceCategory: "Residential Service"
    name: "residential-services"
    folder: "src/services/residential-services"
    slug: "{{pageURL}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page URL", name: "pageURL", widget: "string"}
      - { label: "Snippet", name: "snippet", widget: "string"}
      - { label: "Description", name: "description", widget: "markdown"}
      - { label: "Service Images", name: "image", widget: "image"}
     
      - label: "Features"
        name: "serviceIncludes"
        widget: "list"
        label_singular: "Service Feature"
        collapsed: true
        fields: 
          - { label: "Service Feature", name: "serviceFeature", widget: "string" }

      - label: "Icons"
        name: "serviceIcons"
        widget: "list"
        label_singular: "icon"
        collapsed: true
        fields: 
          - { label: "Service Icon", name: "serviceIcon", widget: "string" }
          - { label: "Icon Title", name: "iconTitle", widget: "string" }

  - label: "New Construction Services"
    serviceCategory: "New Construction Service"
    name: "new-construction-services"
    folder: "src/services/new-construction-services"
    slug: "{{fields.slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page URL", name: "slug", widget: "string"}
      - { label: "Snippet", name: "snippet", widget: "string"}
      - { label: "Description", name: "description", widget: "markdown"}
      - { label: "Service Images", name: "image", widget: "image"}
     
      - label: "Features"
        name: "serviceIncludes"
        widget: "list"
        label_singular: "Service Feature"
        collapsed: true
        fields: 
          - { label: "Service Feature", name: "serviceFeature", widget: "string" }

      - label: "Icons"
        name: "serviceIcons"
        widget: "list"
        label_singular: "icon"
        collapsed: true
        fields: 
          - { label: "Service Icon", name: "serviceIcon", widget: "string" }
          - { label: "Icon Title", name: "iconTitle", widget: "string" }

  

          
  

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }

  - label: "All Widgets"
    name: "allWidgets"
    files:
      - label: "Blog Post Hero Image"
        name: "blogPostHeroImage"
        widget: "list"
        file: "src/_data/settings.yaml"
        fields: 
          - label: Hero Image
            name: heroImage
            widget: object
            minimized_collapsed: true
            allow_add: true
            collapsed: true
            fields:
              - {label: Hero Image, name: image, widget: image}
              - { label: Image Title, name: title, widget: string}
          - label: Post Title
            name: postTitle
            widget: string
          

        